### ISSUE TITLE
frozenset on query

### ISSUE THREAD

**Issue by franciscovargas** [c-w/Gutenberg#22] opened 2015-09-02 21:55 UTC
The query example `(print(get_etexts('title', 'Moby Dick; Or, The Whale')))` is returning frozenset([]) for me is this a current bug or has pip just set this up wrongly ?

**Comment by c-w** [comment] 2015-09-04 11:31
How did you encounter this bug? I haven't been able to reproduce it on Ubuntu Precise when installing Gutenberg from pypi or from source.

Setting up the environment:
```bash
# from pypi
virtualenv venv
. venv/bin/activate
pip install gutenberg

# from source
git clone git@github.com:c-w/Gutenberg.git
cd Gutenberg/
virtualenv venv
. venv/bin/activate
pip install -r requirements.pip
```

Running the code:
```bash
# builds the metadata BDB and then returns `frozenset([2489, 2701, 28794])`
python -c "from gutenberg.query import get_etexts; print(get_etexts('title', 'Moby Dick; Or, The Whale'))"
```

**Comment by hugovk** [comment] 2015-10-29 08:28
I got the same with Python 2.7 on Windows 7, installed with `pip install gutenberg`.

```
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gutenberg.query import get_etexts
INFO:rdflib:RDFLib Version: 4.2.1
>>> from gutenberg.query import get_metadata
>>> print(get_metadata('title', 2701))  # prints 'Moby Dick; Or, The Whale'
frozenset([u'Moby Dick; Or, The Whale'])
>>> print(get_metadata('author', 2701)) # prints 'Melville, Hermann'
frozenset([u'Melville, Hermann'])
>>> print(get_etexts('title', 'Moby Dick; Or, The Whale'))  # prints (2701, ...)
frozenset([2489, 28794, 2701])
>>> print(get_etexts('author', 'Melville, Hermann'))        # prints (2701, ...)
frozenset([2694, 2701, 15, 13720, 13721, 34970, 23969, 12841, 9268, 9269, 8118, 21816, 2489, 9146, 9147, 15422, 4045, 10
712, 11231, 12384, 1900, 28656, 15859, 28794])
>>>
```

**Comment by hugovk** [comment] 2015-10-29 09:33
The code's explicitly returning `frozenset`s:

```python
def get_metadata(feature_name, etextno):
    """Looks up the value of a meta-data feature for a given text.
    Arguments:
        feature_name (str): The name of the meta-data to look up.
        etextno (int): The identifier of the Gutenberg text for which to look
            up the meta-data.
    Returns:
        frozenset: The values of the meta-data for the text or an empty set if
            the text does not have meta-data associated with the feature.
    Raises:
        NotImplementedError: If there is no MetadataExtractor registered that
            can extract meta-data for the given feature name.
    """
    metadata_values = MetadataExtractor.get(feature_name).get_metadata(etextno)
    return frozenset(metadata_values)


def get_etexts(feature_name, value):
    """Looks up all the texts that have meta-data matching some criterion.
    Arguments:
        feature_name (str): The the meta-data on which to select the texts.
        value (str): The value of the meta-data on which to filter the texts.
    Returns:
        frozenset: The set of all the Project Gutenberg text identifiers that
            match the provided query.
    Raises:
        NotImplementedError: If there is no MetadataExtractor registered that
            can extract meta-data for the given feature name.
    """
    matching_etexts = MetadataExtractor.get(feature_name).get_etexts(value)
    return frozenset(matching_etexts)
```

https://github.com/c-w/Gutenberg/blob/master/gutenberg/query/api.py#L18-L56

**Comment by c-w** [comment] 2015-11-01 20:18
Given that we can't reproduce this bug, I'm going to close this for now.

@franciscovargas: please re-open the issue when you can tell us more about how to reproduce the issue.

**Comment by hugovk** [comment] 2015-11-01 20:22
@c-w I can reproduce it. What more info would be helpful (other than my comments above)? Thanks.

**Comment by hugovk** [comment] 2015-11-03 08:19
Here's a workaround for anyone else who encounters this bug:
```python
def fronzenhack(metadata):
    """Workaround for https://github.com/c-w/Gutenberg/issues/22
    get_metadata('author', 2701) returns frozenset([u'Melville, Hermann'])
    instead of 'Melville, Hermann'.
    """
    try:
        return list(metadata)[0]
    except IndexError:
        return None

title = fronzenhack(get_metadata('title', 2701))
author = fronzenhack(get_metadata('author', 2701))
```

**Comment by c-w** [comment] 2015-11-06 22:25
@hugovk: I don't think you're describing the same issue as @franciscovargas.

Francisco commented that the `get_metadata('author', 2701)` call returned an *empty results set*.
You commented that the `get_metadata('author', 2701)` call returns a *set with a single entry*. If reproducible, the former is a bug; the later, however, is working as expected.

The `get_metadata` call returns a set because a book can have multiple authors, titles, etc, but it wouldn't make sense for the call to return the same piece of information twice; hence a set is the semantically appropriate data-structure.

If you know that the book for which you are retrieving meta-data such as authors only has a single author, using a helper function (like your `frozenhack`) to unpack the only element in the set makes sense. However, for the sake of consistency in the API, I assert that it should be the responsibility of clients of the library to do this unpacking, especially since it's as simple as `next(iter(get_metadata('author', 2701)))`.

**Comment by hugovk** [comment] 2015-11-06 22:36
@c-w Right you are, thanks for clearing that up! The README documentation could be a little clearer, it suggests strings and tuples are returned.

**Comment by yever** [comment] 2015-11-20 21:07
I'm getting the same issue on Ubuntu 14.04:

```sh
$ python -c "from gutenberg.query import get_etexts; print(get_etexts('title', 'Moby Dick; Or, The Whale'))"
INFO:rdflib:RDFLib Version: 4.2.1
frozenset([])
```

**Comment by c-w** [comment] 2015-11-23 19:22
Re-opening to investigate.

**Comment by franciscovargas** [comment] 2016-05-29 21:25
I dont know what more info can I provide I installed gutenberg using pip in scientific linux now and it still gives me the same errors:


    >>> from gutenberg.query import get_etexts
    >>> from gutenberg.query import get_metadata
    >>> print(get_metadata('title', 2701)) 
        frozenset([])


These are examples from the docs in pipy

**Comment by c-w** [comment] 2017-02-19 08:02
@franciscovargas With the latest [0.4.5](https://pypi.python.org/pypi/Gutenberg/0.4.5) release, I can't reproduce this bug any more so I'm closing this. Please let me know and re-open if you're still facing this issue.

Steps (as per ReadMe):

1. Install the latest version of the library:
  `pip install gutenberg==0.4.5`

2. Setup the metadata:
  `python -c "from gutenberg.acquire import get_metadata_cache; get_metadata_cache().populate()"`

3. Query the data:
  `python -c "from gutenberg.query import get_metadata; print(get_metadata('title', 2701))"`

4. Observe the correct output:
  `frozenset([u'Moby Dick; Or, The Whale'])`

**Closed by c-w** 2017-02-19 08:02 UTC
Labels: bug
